version: '3.9'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_DB: escola_cici
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PG_DATA: /var/lib/postgresql/data
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        container_name: database_cici
volumes:
    pgdata: